name: Bodyshop Revolution
favicon: null
layout_spectrum: 0.9720719149336219
typography_spectrum: 0.508759951684624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbd500'
    - '#007895'
    - '#000000'
    - '#00ff00'
    - '#808000'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
